package com.example.abschlussprojekt_husewok.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.LocalDate
import java.time.format.DateTimeFormatter

@Entity(tableName = "housework_table")
data class Housework(
    // Primary key for the housework entry, auto-generated by the database
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // Image resource ID for the housework
    val image: Int,

    // Title of the housework
    val title: String,

    // Description of the housework
    val description: String,

    // Boolean if task is liked by user
    var isLiked: Boolean = true,

    // Locked days of the housework
    var lockDurationDays: Long,

    // Lock expiration date of the housework
    var lockExpirationDate: String? = null,
) {
    /**
     * Checks if the lock is currently active.
     *
     * @return true if the lock is active, false otherwise.
     */
    fun isLocked(): Boolean {
        var lockExpirationDateAsDate: LocalDate?
        lockExpirationDate?.let {
            lockExpirationDateAsDate = LocalDate.parse(it, DateTimeFormatter.ISO_LOCAL_DATE)
            return LocalDate.now().isBefore(lockExpirationDateAsDate)
        }
        return false
    }

    /**
     * Updates the lock expiration date based on the current date and the lock duration.
     */
    fun updateLockExpirationDate() {
        val lockExpirationDateAsDate = LocalDate.now().plusDays(lockDurationDays)
        lockExpirationDate = lockExpirationDateAsDate.format(DateTimeFormatter.ISO_LOCAL_DATE)
    }
}